name = "digital-objects"
version = "0.1.0"
defaultTargets = ["DigitalObjects"]

[[lean_lib]]
name = "DigitalObjects"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.1"

[[leanOptions]]
# better error messages for a newbie like me.  Forces writing implicit
# arguments with '{ ... }' notation, but gives better error messages when
# using undefined symbols.
name = "autoImplicit"
value = false
